project:
  type: website
  output-dir: site

execute:
  freeze: auto   # important for reproducibility

site-url: "https://patwuch.github.io/Chuang_Lab_TMU/"

website:
  title: "Chuang Lab TMU"
  description: "Chuang Lab TMU"
  favicon: "images/tmu-logo.png"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Dengue Infection Data Module"
        href: dengue-infection-module/report/index.qmd
      - text: "Shared Socioeconomic Pathways Module"
        href: climate-projection-module/report/index.qmd
      - text: "Zonal Statistics Earth Observation Module"
        href: zonal-statistics-module/report/index.qmd
      - text: "Machine Learning Epidemiology Prediction Module"
        href: machine-learning-module/report/index.qmd
